# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k7jyDh_bcT49Wl1288X3yhrvmdWcQkAR
"""

print('    *    ')
print('   ***   ')
print('  *****  ')
print('*********')
print('  *****  ')
print('   ***   ')
print('    *    ')